meta_product_name: "Quickfeedr"
meta_title: "Quickfeedr - Jobs made easy"
meta_description: "Quickfeedr helps you manage employment listings easily. Whether you're a recruiter or
a potential employee, your productivity will be improved instantly"
meta_image: "money.jpg" # should exist in `app/assets/images/`